[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.15", features = ["blocking", "json"]}
rusqlite = {version = "0.35.0", features = ["bundled"] }
serde_json = "1.0.140"
